spring:
  application:
    name: game-booking

  # database connection
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://161.248.146.42:25100/db_gamebooking_dev?createDatabaseIfNotExist=true&serverTimezone=Asia/Ho_Chi_Minh
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Ho_Chi_Minh

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  # email
  mail:
    host: smtp.gmail.com
    port: 587
    username: fptgbsystem@gmail.com
    password: xuaz lmnu swqs peau
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  app:
    base-url: https://fptgamebooking.vn

# security
jwtSecret: "mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm"
jwtExpirationMs:
  Token: 86400000
  RefreshToken: 604800000

logging:
  level:
    org:
      springframework:
        transaction: DEBUG
      hibernate:
        SQL: DEBUG

cloudinary:
  cloudName: "db8h1vnhj"
  apiKey: "652637162123458"
  apiSecret: "9zLG59ruEvs4KlMzpxT1FFd4xEg"

gemini:
  apiKey: "AIzaSyCbqUQxmy3FfUJcn2G7JvY_YAlkTzIgtpA"