spring:
  application:
    name: game-booking

  # database connection
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://157.66.27.80:3306/db_gamebooking?createDatabaseIfNotExist=true
    username: admin
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  # email
  app:
    base-url: https://fptgamebooking.vn

  mail:
    host: smtp.gmail.com
    port: 587
    username: fptgamebooking@gmail.com
    password: cpjw kxqu atyp deek
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


# security
jwtSecret: "mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm"
jwtExpirationMs:
  Token: 86400000
  RefreshToken: 604800000

logging:
  level:
    org:
      springframework:
        transaction: DEBUG
      hibernate:
        SQL: DEBUG

